"""The case report PDF: everything a reviewer sees on the case screen, on paper."""

from __future__ import annotations

from backend.reports.common import (
    BULLET,
    H1,
    H2,
    H3,
    PAGE_WIDTH,
    cell,
    clean,
    head_row,
    para,
    render,
    table,
)  # fmt: skip

CLAIM_ID_LIMIT = 12
ROW_LIMIT = 40
HIDDEN_EVENTS = {"brief", "notification", "email_attempt"}


def _rupees(n) -> str:
    return f"Rs {round(n or 0):,}"


def _ids(ids: list[str]) -> str:
    shown = ", ".join(ids[:CLAIM_ID_LIMIT])
    return shown + (f" (+{len(ids) - CLAIM_ID_LIMIT} more)" if len(ids) > CLAIM_ID_LIMIT else "")


def _brief_story(text: str) -> list:
    story = []
    for raw in text.splitlines():
        line = raw.strip().replace("**", "")
        if not line:
            continue
        if line.startswith("## "):
            story.append(para(line[3:], H3))
        elif line.startswith("# "):
            continue
        elif line[:2] in {"- ", "* "}:
            story.append(para(line[2:], BULLET))
        else:
            story.append(para(line))
    return story


def build_case_report(
    *, detail, item, brief, graph, events, access, generated_by: str, generated_at: str
) -> bytes:  # fmt: skip
    """`detail` is the CaseDetail, `item` its queue row (priority factors), `brief` the BriefOut,
    `graph` the GraphOut, `events` the audit entries for the case, `access` the AccessOut."""
    story = [para(f"Case report: {detail.case_id}", H1), para(detail.title)]
    header = [
        ["Case ID", detail.case_id, "Type", detail.case_type],
        ["Unit", access.unit_name or "Unrouted", "Assignee", access.assignee_name or "Not assigned"],
        ["Case status", access.assignment_status.replace("_", " "), "Review status", detail.status],
        ["Generated by", generated_by, "Generated at", generated_at],
    ]
    story.append(table([[cell(c) for c in row] for row in header],
                       [PAGE_WIDTH * f for f in (0.16, 0.34, 0.16, 0.34)], header=False))  # fmt: skip

    story.append(para("Priority", H2))
    story.append(para(
        f"Queue rank {detail.rank} ({detail.queue}). Priority {detail.priority:.3f}; AI priority "
        f"{detail.ai_priority:.3f}" + (f"; overridden by {detail.override.reviewer}: {detail.override.reason}"
                                       if detail.override else "") + ". "
        f"{len(detail.detectors_fired)} of 3 detectors agree. {_rupees(detail.flagged_amount)} flagged "
        f"across {len(detail.affected_members)} members."))  # fmt: skip
    if item is not None:
        f = item.factors
        story.append(table(
            [head_row(["Risk", "Dollars", "Impact", "Severity", "Evidence"]),
             [cell(f"{v:.2f}") for v in (f.risk, f.dollars, f.impact, f.severity, f.evidence)]],
        ))  # fmt: skip

    story.append(para("Evidence", H2))
    rows = [head_row(["Key", "Evidence ID", "Detector", "Entity", "Severity", "Reason", "Claim IDs"])]
    for finding in detail.findings:
        rows.append([cell(finding.key or "-"), cell(finding.finding_id), cell(finding.detector),
                     cell(finding.entity_id), cell(finding.severity), cell(finding.reason),
                     cell(_ids(finding.evidence_ids))])  # fmt: skip
    story.append(table(rows, [PAGE_WIDTH * f for f in (0.05, 0.11, 0.09, 0.1, 0.07, 0.34, 0.24)]))

    story.append(para("Timeline", H2))
    if detail.timeline:
        rows = [head_row(["Dates", "Event", "Claims", "Amount", "Evidence"])]
        for t in detail.timeline:
            span = t.date if t.date == t.end_date else f"{t.date} to {t.end_date}"
            rows.append([cell(span), cell(f"{t.kind}: {t.description}"), cell(t.count),
                         cell(_rupees(t.amount)), cell(", ".join(t.evidence_keys))])  # fmt: skip
        story.append(table(rows, [PAGE_WIDTH * f for f in (0.19, 0.46, 0.08, 0.14, 0.13)]))
    else:
        story.append(para("No dated events."))

    story.append(para("Network summary", H2))
    story.append(para(f"{len(graph.nodes)} nodes and {len(graph.links)} links; "
                      f"{graph.member_count} members{' (grouped)' if graph.members_collapsed else ''}."))  # fmt: skip
    rows = [head_row(["Entity", "Type", "Label", "Suspicious"])]
    rows += [[cell(n.id), cell(n.type), cell(n.label), cell("yes" if n.suspicious else "no")]
             for n in graph.nodes[:ROW_LIMIT]]  # fmt: skip
    story.append(table(rows, [PAGE_WIDTH * f for f in (0.22, 0.2, 0.46, 0.12)]))
    rows = [head_row(["From", "To", "Link", "Weight", "Suspicious"])]
    rows += [[cell(link.source), cell(link.target), cell(link.type), cell(f"{link.weight:g}"),
              cell("yes" if link.suspicious else "no")] for link in graph.links[:ROW_LIMIT]]  # fmt: skip
    story.append(table(rows, [PAGE_WIDTH * f for f in (0.26, 0.26, 0.22, 0.12, 0.14)]))
    if len(graph.nodes) > ROW_LIMIT or len(graph.links) > ROW_LIMIT:
        story.append(para(f"Only the first {ROW_LIMIT} rows of each table are shown.", BULLET))

    story.append(para("Investigation risk", H2))
    for key in sorted(detail.predictions or {"30": detail.prediction}, key=int):
        p = (detail.predictions or {"30": detail.prediction})[key]
        if p.available:
            story.append(para(
                f"{key}-day investigation risk {p.investigation_risk:.1%}, band {p.risk_band} "
                f"(band source: {p.band_source}). {p.band_reason or ''}"))  # fmt: skip
            if p.top_drivers:
                story.append(para("Main drivers: " + "; ".join(p.top_drivers), BULLET))
            if p.note:
                story.append(para(p.note, BULLET))
        else:
            story.append(para(f"{key}-day investigation risk not available: {p.reason or 'Insufficient data'}."))
    story.append(para(f"Confidence: {detail.confidence.get('level', 'n/a')}. "
                      "This is an estimate to help order the queue, not a finding about any person."))  # fmt: skip

    story.append(para("Brief", H2))
    label = f"{brief.provider_label} (model {brief.model})" if brief.source == "llm" else "Template"
    story.append(para(f"Source: {label}" + ("; generated from masked data" if brief.masked else ""), BULLET))
    story += _brief_story(brief.brief)

    story.append(para("Decisions and audit history", H2))
    shown = [e for e in events if e["event_type"] not in HIDDEN_EVENTS]
    if shown:
        rows = [head_row(["When", "Event", "Action", "By", "Reason"])]
        for e in shown:
            rows.append([cell(e["ts"]), cell(e["event_type"].replace("_", " ")), cell(e.get("action") or ""),
                         cell(e.get("reviewer") or ""), cell(e.get("reason") or "")])  # fmt: skip
        story.append(table(rows, [PAGE_WIDTH * f for f in (0.17, 0.17, 0.19, 0.17, 0.30)]))
    else:
        story.append(para("Nothing has been recorded for this case yet."))

    story.append(para("Limitations", H2))
    story += [para(text, BULLET) for text in detail.limitations] or [para("None recorded.")]
    return render(story, f"Case report {clean(detail.case_id)}")
